version: "2"
services:
  web: 
    #build: .
    image: csvitor/php7.3:1.1
    container_name: "web-csvitor"
    ports: 
      - "80:80"
    links: 
      - "db"
    volumes: 
      - "./src:/var/www/html"
    environment:
      - DOCKER_PHP_MEMORY_LIMIT=2048M
      - DOCKER_PHP_MAX_EXECUTION_TIME=38000
      - DOCKER_PHP_DATA_TIMEZONE=UTC
      - DOCKER_PHP_UPLOAD_FILESIZE=128M
      - DOCKER_PHP_ALWAYS_POPULATE_RAW_POST_DATA=-1
      - DOCKER_PHP_ZLIB_OUTPUT_COMPRESSION=on
      - DOCKER_PHP_LOG_ERRORS=On
      - DOCKER_PHP_DISPLAY_ERRORS=On
      - DOCKER_PHP_SENDMAIL_PATH=/opt/go/bin/mhsendmail --smtp-addr='mailhog:1025'
  db:
    image: mysql:8.0.19
    container_name: "db-csvitor"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '3306:3306'
    volumes: 
      - "./database:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'docker_csvitor'
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: "phpmyadmin-l"
    links:
        - "db"
    ports:
        - 8080:80
    environment:
        - PMA_ARBITRARY=1
  mailhog:
    image: mailhog/mailhog
    container_name: "mailhog-csvitor"
    ports:
      - 1025:1025
      - 8025:8025
